version: '3.8'

services:
  app:
    container_name: numismatic-app
    build: .
    command: ./app
    ports:
      - "81:80"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=coins
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  mongo:
    restart: no
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=coins
    ports:
      - "27019:27017"
    command:
      mongod

  redis:
    restart: no
    image: redis:latest
    ports:
      - "6379:6379"