version: '3.8'

services:
  app:
    container_name: numismatic-app
    build: .
    command: ./app
    ports:
      - "81:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: no
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s