version: '3.8'

services:
  app:
    container_name: numismatic-app
    build: .
    command: ./app
    ports:
      - "81:80"
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DATABASE=coins

  db:
    restart: no
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=coins
    ports:
      - "27019:27017"
    command:
      mongod