name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run the app container
        run: |
          docker-compose up -d --build app
          # Подождите, пока MongoDB будет готова
          until docker exec mongo mongo --eval "print(\"waited for connection\")"; do sleep 1; done

      - name: Run tests
        run: |
          docker-compose exec app go test ./tests

      - name: Stop and remove containers
        run: docker-compose down
