name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services
        run: |
          docker-compose up -d --build

      - name: Show MongoDB logs (initial check)
        run: docker logs numismaticclubapi-mongo-1 || true

      - name: Wait for MongoDB to be ready
        run: |
          retries=30
          until docker exec numismaticclubapi-mongo-1 mongo --eval "db.stats()" > /dev/null 2>&1; do
            if [ $retries -le 0 ]; then
              echo "MongoDB failed to start."
              exit 1
            fi
            echo "Waiting for MongoDB to start..."
            retries=$((retries - 1))
            sleep 3
          done

      - name: Run tests
        run: |
          docker exec numismatic-app go test ./tests

      - name: Show MongoDB logs (post-check)
        run: docker logs numismaticclubapi-mongo-1 || true

      - name: Stop and remove containers
        run: |
          docker-compose down
